# Generated by Django 5.0.3 on 2024-03-19 10:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNSURE', 'Unsure')], default='UNSURE', max_length=6)),
                ('ethnicity', models.CharField(choices=[('CHHETRI', 'Chhetri'), ('BRAHMAN', 'Brahman'), ('MAGAR', 'Magar'), ('THARU', 'Tharu'), ('TAMANG', 'Tamang'), ('BISHWOKARMA', 'Bishwokarma'), ('MUSALMAN', 'Musalman'), ('NEWAR', 'Newar'), ('YADAV', 'Yadav'), ('RAI', 'Rai'), ('PARIYAR', 'Pariyar'), ('GURUNG', 'Gurung'), ('THAKURI', 'Thakuri'), ('MIJAR', 'Mijar'), ('TELI', 'Teli'), ('LIMBU', 'Limbu'), ('HARIJAN', 'Harijan'), ('KUSHWAHA', 'Kushwaha')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must start with 9 and have exactly 10 digits', regex='^9\\d{9}$')])),
                ('demographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.demographics')),
            ],
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_description', models.TextField()),
                ('accessories', models.TextField()),
                ('demographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.demographics')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_class', models.CharField(max_length=20)),
                ('is_solved', models.BooleanField(default=False)),
                ('demographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.demographics')),
            ],
        ),
        migrations.CreateModel(
            name='Circumstances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_date', models.DateField()),
                ('last_contact_date', models.DateField()),
                ('last_known_location', models.CharField(choices=[('BHOJPUR', 'Bhojpur'), ('DHANKUTA', 'Dhankuta'), ('ILAM', 'Ilam'), ('JHAPA', 'Jhapa'), ('KHOTANG', 'Khotang'), ('MORANG', 'Morang'), ('OKHALDHUNGA', 'Okhaldhunga'), ('PANCHTHAR', 'Panchthar'), ('SANKHUWASABHA', 'Sankhuwasabha'), ('SOLUKHUMBU', 'Solukhumbu'), ('SUNSARI', 'Sunsari'), ('TAPLEJUNG', 'Taplejung'), ('TEHRATHUM', 'Tehrathum'), ('UDAYAPUR', 'Udayapur'), ('PARSA', 'Parsa'), ('BARA', 'Bara'), ('RAUTAHAT', 'Rautahat'), ('SARLAHI', 'Sarlahi'), ('DHANUSHA', 'Dhanusha'), ('SIRAHA', 'Siraha'), ('MAHOKTARI', 'Mahottari'), ('SAPTARI', 'Saptari'), ('SINDHULI', 'Sindhuli'), ('RAMECHHAP', 'Ramechhap'), ('DOLKHA', 'Dolakha'), ('BHaktapur', 'Bhaktapur'), ('DHADING', 'Dhading'), ('KATHMANDU', 'Kathmandu'), ('KAVREPALANCHOK', 'Kavrepalanchok'), ('LAILAPUR', 'Lalitpur'), ('NUWAKOT', 'Nuwakot'), ('RASUWA', 'Rasuwa'), ('SINDHUPALCHOK', 'Sindhupalchok'), ('CHITWAN', 'Chitwan'), ('MAKWANPUR', 'Makwanpur'), ('BAGLUNG', 'Baglung'), ('GORKHA', 'Gorkha'), ('KASKI', 'Kaski'), ('LAMJUNG', 'Lamjung'), ('MANANG', 'Manang'), ('MUSTANG', 'Mustang'), ('MYAGDI', 'Myagdi'), ('NAWALPARASI_EAST', 'Nawalparasi East'), ('PARBAT', 'Parbat'), ('SYANGJA', 'Syangja'), ('TANAHUN', 'Tanahun'), ('KAPILVASTU', 'Kapilvastu'), ('NAWALPARAI_WEST', 'Nawalparai West'), ('RUPANDEHI', 'Rupandehi'), ('ARGHAKHANCHI', 'Arghakhanchi'), ('GULMI', 'Gulmi'), ('PALPA', 'Palpa'), ('DANI', 'Dang'), ('PYUTHAN', 'Pyuthan'), ('ROPA', 'Rolpa'), ('EASTERN_RUKUM', 'Eastern Rukum'), ('BAIKE', 'Baike'), ('BARDIYA', 'Bardiya'), ('WESTERN_RUKUM', 'Western Rukum'), ('SALYAN', 'Salyan'), ('DOLPA', 'Dolpa'), ('HUMLA', 'Humla'), ('JUMLA', 'Jumla'), ('KAILALI', 'Kailali'), ('ACHAM', 'Achham'), ('DOTI', 'Doti'), ('BAJHANG', 'Bajhang'), ('BAJURA', 'Bajura'), ('KANCHANPUR', 'Kanchanpur'), ('DADELDHURA', 'Dadeldhura'), ('BAITADI', 'Baitadi')], max_length=20)),
                ('notes', models.TextField()),
                ('aggravating_factors', models.CharField(choices=[('HELP_REQUESTED', 'Help'), ('FIGHT_OVERHEARD', 'Fight'), ('ACCIDENT_SOUNDS', 'Accident'), ('CHILD', 'Child'), ('MENTAL_ILLNESS', 'Mental Illness')], max_length=20)),
                ('demographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.demographics')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('demographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.demographics')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair_color', models.CharField(choices=[('BLOND', 'Blond'), ('DARK_BROWN', 'Dark Blond'), ('MEDIUM_BROWN', 'Medium Brown'), ('DARK_BROWN', 'Dark Brown'), ('REDDISH_BROWN', 'Reddish Brown'), ('RED', 'Red'), ('BLACK', 'Black'), ('GRAY', 'Gray'), ('WHITE', 'White')], max_length=20)),
                ('hair_description', models.TextField()),
                ('eye_color', models.CharField(choices=[('BROWN', 'Brown'), ('BLUE', 'Blue'), ('HAZEL', 'Hazel'), ('AMBER', 'Amber'), ('GRAY', 'Gray'), ('GREEN', 'Green')], max_length=20)),
                ('eye_description', models.TextField()),
                ('height', models.IntegerField(help_text='Height in centimeters')),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('paralysis', models.BooleanField(default=False)),
                ('demographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.demographics')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_manufacturer', models.CharField(max_length=20)),
                ('vehicle_style', models.CharField(choices=[('MICROBUS', 'Microbus'), ('MINIBUS', 'Minibus'), ('E_RIKSHAW', 'E-Rikshaw'), ('BUS', 'Bus'), ('TRUCK', 'Truck'), ('PICKUP', 'Pickup'), ('TRACTOR', 'Tractor'), ('TEMPO', 'Tempo'), ('CAR', 'Car'), ('JEEP', 'Jeep'), ('VAN', 'Van'), ('MOTORCYCLE', 'Motorcycle')], max_length=20)),
                ('vehicle_color', models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black'), ('GRAY', 'Gray'), ('SILVER', 'Silver'), ('BLUE', 'Blue'), ('RED', 'Red'), ('BROWN', 'Brown'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('BEIGE', 'Beige'), ('PURPLE', 'Purple'), ('GOLD', 'Gold'), ('YELLOW', 'Yellow')], max_length=20)),
                ('manufacture_year', models.IntegerField()),
                ('registration_state', models.CharField(choices=[('KOSHI', 'Koshi'), ('MADHESH', 'Madhesh'), ('BAGMATI', 'Bagmati'), ('GANDAKI', 'Gandaki'), ('LUMBINI', 'Lumbini'), ('KARNALI', 'Karnali'), ('SUDURPASCHIM', 'Sudurpaschim')], max_length=20)),
                ('notes', models.TextField()),
                ('demographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.demographics')),
            ],
        ),
    ]
