# Generated by Django 5.0.3 on 2024-03-24 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('chosen_name', models.CharField(max_length=50)),
                ('age_type', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biological_sex', models.CharField(max_length=15)),
                ('race_ethnicity', models.CharField(max_length=50)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.identifications')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=10)),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_relation', models.CharField(max_length=50)),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.identifications')),
            ],
        ),
        migrations.CreateModel(
            name='Clothings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_description', models.TextField()),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.identifications')),
            ],
        ),
        migrations.CreateModel(
            name='Classifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_class', models.CharField(max_length=50)),
                ('is_solved', models.BooleanField()),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.identifications')),
            ],
        ),
        migrations.CreateModel(
            name='Circumstances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_date', models.DateField()),
                ('last_contact_date', models.DateField()),
                ('circumstances_note', models.TextField()),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.identifications')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.identifications')),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.identifications')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair_color', models.CharField(max_length=50)),
                ('hair_description', models.TextField()),
                ('eye_color', models.CharField(max_length=50)),
                ('eye_description', models.TextField()),
                ('distinctive_physical_features', models.TextField()),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.identifications')),
            ],
        ),
        migrations.CreateModel(
            name='Transports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('registration_state', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50)),
                ('vehicle_note', models.TextField()),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.identifications')),
            ],
        ),
    ]
