# Generated by Django 5.0.3 on 2024-03-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationresult',
            name='is_solved',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='classificationresult',
            name='predicted_class',
            field=models.CharField(choices=[('PANIC', 'Panic'), ('WAIT', 'Wait'), ('CRITICAL', 'Critical'), ('SERIAL', 'Serial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='physicaldescription',
            name='paralysis',
            field=models.BooleanField(),
        ),
    ]
