# Generated by Django 5.0.4 on 2024-04-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="manufacture_year",
            field=models.IntegerField(null=True),
        ),
    ]
