# Generated by Django 5.0.3 on 2024-03-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identifications',
            name='age_type',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='descriptions',
            name='race_ethnicity',
            field=models.CharField(max_length=70),
        ),
    ]
