# Generated by Django 5.0.3 on 2024-03-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_classificationresult_is_solved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circumstances',
            name='aggravating_factors',
            field=models.BooleanField(default=False, help_text='Is there any aggravating factors?'),
        ),
        migrations.AlterField(
            model_name='classificationresult',
            name='predicted_class',
            field=models.CharField(choices=[('PANIC', 'Panic'), ('REAL', 'Real'), ('CRITICAL', 'Critical'), ('SERIAL', 'Serial')], max_length=20),
        ),
    ]
