# Generated by Django 5.0.4 on 2024-04-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_vehicle_manufacture_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="manufacture_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
