# Generated by Django 5.0.3 on 2024-03-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_identifications_age_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identifications',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
