# Generated by Django 5.0.4 on 2024-04-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_vehicle_manufacture_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="image",
        ),
        migrations.AddField(
            model_name="photo",
            name="image_data",
            field=models.TextField(null=True),
        ),
    ]
