# Generated by Django 5.0.4 on 2024-04-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_photo_image_photo_image_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="image_data",
        ),
        migrations.AddField(
            model_name="photo",
            name="image",
            field=models.ImageField(null=True, upload_to="image/"),
        ),
    ]
